In [1]:
import numpy as np

In [2]:
python_list = [1,2,3,5,-5]

In [3]:
python_list

[1, 2, 3, 5, -5]

In [4]:
nump_arr = np.array(python_list)

In [5]:
nump_arr

array([ 1,  2,  3,  5, -5])

In [6]:
nump_arr.shape

(5,)

In [7]:
len(nump_arr.shape)

1

In [8]:
python_list_list = [[1,2],[3,4]] 

In [9]:
python_list_list

[[1, 2], [3, 4]]

In [10]:
nump_arr2d = np.array(python_list_list)

In [11]:
nump_arr2d

array([[1, 2],
       [3, 4]])

In [12]:
nump_arr2d.shape

(2, 2)

In [13]:
len(nump_arr2d)

2

In [14]:
len(nump_arr2d.shape)

2

In [15]:
python_list_list = [[1,2,5],[3,4,6]] 

In [16]:
np.array(python_list_list).shape

(2, 3)

In [17]:
range(5)

range(0, 5)

In [18]:
list(range(5))

[0, 1, 2, 3, 4]

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [25]:
np.ones((2,2,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [26]:
np.random

<module 'numpy.random' from '/opt/homebrew/Cellar/jupyterlab/4.1.2/libexec/lib/python3.12/site-packages/numpy/random/__init__.py'>

In [27]:
np.random.randint

<function RandomState.randint>

In [28]:
np.random.randint(5)

1

In [29]:
np.random.randint((10,10,100))

array([ 9,  1, 44])

In [30]:
np.random.randint((10), size=(2,2))

array([[7, 8],
       [4, 4]])

In [31]:
np.random.randint((10,2), size=(2,2))

array([[5, 0],
       [2, 1]])

In [36]:
np.random.randint((10,2,99), size=(2,2,3))

array([[[ 5,  0, 42],
        [ 9,  1, 53]],

       [[ 3,  1, 77],
        [ 2,  1, 30]]])

In [33]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [34]:
help()

Welcome to Python 3.12's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".



help>  q



You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [37]:
a = [1,2,3,4]

In [51]:
arr = np.array(a)

In [52]:
arr

array([1, 2, 3, 4])

In [53]:
arr.dtype

dtype('int64')

In [56]:
a = [1.2,3.4,5.2,3.3,6]

In [57]:
type(a[-1])

int

In [58]:
type(a[0])

float

In [60]:
arr2 = np.array(a)

In [61]:
arr2

array([1.2, 3.4, 5.2, 3.3, 6. ])

In [62]:
type(arr2[0])

numpy.float64

In [63]:
type(arr2[-1])

numpy.float64

In [76]:
a = [1.2,3.4,5.2,3.3,6,"4"]

In [77]:
a

[1.2, 3.4, 5.2, 3.3, 6, '4']

In [78]:
type(a[0])

float

In [79]:
type(a[-1])

str

In [80]:
arr3 = np.array(a)

In [81]:
arr3

array(['1.2', '3.4', '5.2', '3.3', '6', '4'], dtype='<U32')

In [82]:
type(arr3[0])

numpy.str_

In [83]:
type(arr3[-1])

numpy.str_

In [84]:
a = [1.2,3.4,5.2,3.3,6]

In [85]:
a

[1.2, 3.4, 5.2, 3.3, 6]

In [86]:
arr4 = np.array(a)

In [87]:
arr4

array([1.2, 3.4, 5.2, 3.3, 6. ])

In [91]:
arr4.astype(np.int32)

array([1, 3, 5, 3, 6], dtype=int32)

In [93]:
arr4.astype(np.int32).dtype

dtype('int32')

In [94]:
arr4.astype(np.int8)

array([1, 3, 5, 3, 6], dtype=int8)

In [97]:
arr4.astype(np.int8).dtype

dtype('int8')

In [100]:
arr4.astype(int)

array([1, 3, 5, 3, 6])

In [101]:
arr4.astype(int).dtype

dtype('int64')

# Numpy slicing

In [102]:
import numpy as np

In [103]:
arr = np.random.rand(5,5)

In [104]:
arr

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436],
       [0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514]])

In [106]:
arr.shape

(5, 5)

In [107]:
np.shape(arr)

(5, 5)

In [108]:
len(arr)

5

In [109]:
np.shape(arr)[0]

5

In [110]:
arr.dtype

dtype('float64')

In [111]:
arr[:4]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436]])

In [113]:
arr[4,4]

0.27167513536166743

In [114]:
arr[:4].shape

(4, 5)

In [116]:
arr[4,4].shape

()

In [117]:
arr[4:]

array([[0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514]])

In [118]:
arr[4:].shape

(1, 5)

In [119]:
arr[:]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436],
       [0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514]])

In [120]:
arr[:-1]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436]])

In [121]:
arr[-1]

array([0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514])

In [122]:
arr[-1:]

array([[0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514]])

In [123]:
arr[:-2]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712]])

In [127]:
#last column
arr[:,-1]

array([0.28525008, 0.37876008, 0.65615712, 0.40251436, 0.27167514])

In [128]:
#last row
arr[-1,:]

array([0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514])

In [129]:
arr

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436],
       [0.10786068, 0.54477534, 0.70318774, 0.73920046, 0.27167514]])

In [132]:
#2nd last column
arr[:,-2]

array([0.6303495 , 0.55612651, 0.17137576, 0.41957636, 0.73920046])

In [135]:
#without last column
arr[:,:-1]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 ],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636],
       [0.10786068, 0.54477534, 0.70318774, 0.73920046]])

In [137]:
#without last column
arr[:,:4]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 ],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636],
       [0.10786068, 0.54477534, 0.70318774, 0.73920046]])

In [144]:
#without last row
arr[:4,:]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436]])

In [145]:
#without last row
arr[:-1,:]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008],
       [0.94083193, 0.87297256, 0.85286752, 0.55612651, 0.37876008],
       [0.90405662, 0.46012473, 0.90563732, 0.17137576, 0.65615712],
       [0.43118075, 0.78566669, 0.65640321, 0.41957636, 0.40251436]])

In [146]:
 #only 1st row
arr[:--1,:]

array([[0.57219047, 0.54644941, 0.06321264, 0.6303495 , 0.28525008]])

In [147]:
int_arr = np.random.randint(5, size=(6,8))

In [148]:
int_arr

array([[2, 0, 4, 1, 2, 2, 4, 1],
       [2, 2, 3, 2, 2, 3, 0, 4],
       [1, 4, 0, 0, 4, 1, 1, 3],
       [0, 4, 3, 1, 4, 2, 0, 2],
       [3, 0, 4, 2, 2, 1, 4, 4],
       [2, 4, 4, 3, 4, 1, 4, 3]])

In [149]:
int_arr_0 = int_arr[0]

In [150]:
int_arr_0

array([2, 0, 4, 1, 2, 2, 4, 1])

In [152]:
 (int_arr_0 == 0) | (int_arr_0 == 1) | (int_arr_0 == 2)

array([ True,  True, False,  True,  True,  True, False,  True])

In [167]:
(int_arr_0 == 0)

array([False,  True, False, False, False, False, False, False])

In [168]:
(int_arr_0 == 1)

array([False, False, False,  True, False, False, False,  True])

In [169]:
(int_arr_0 == 2)

array([ True, False, False, False,  True,  True, False, False])

In [165]:
bool_arr_0 = False
for i in range(3):
    bool_arr_0 = bool_arr_0 | (int_arr_0 == i)
    print(bool_arr_0)

[False  True False False False False False False]
[False  True False  True False False False  True]
[ True  True False  True  True  True False  True]


In [166]:
bool_arr_0

array([ True,  True, False,  True,  True,  True, False,  True])

In [164]:
# bool_arr_0 = True
# for i in range(3):
#     bool_arr_0 = bool_arr_0 | (int_arr_0 == i)

In [163]:
# bool_arr_0

In [171]:
int_arr_0

array([2, 0, 4, 1, 2, 2, 4, 1])

In [172]:
int_arr_0[bool_arr_0]

array([2, 0, 1, 2, 2, 1])

# Numpy Matrix operations

In [173]:
import numpy as np

In [175]:
marks = [[11,23,23,22],[22,12,23,19],[25,24,24,24]]

In [176]:
marks[0][0]

11

In [177]:
marks[0]

[11, 23, 23, 22]

In [178]:
marks[0][0], marks[1][0], marks[2][0]

(11, 22, 25)

In [179]:
len(marks)

3

In [182]:
len(marks[0])

4

In [190]:
marks_transpose = []
for j in range(len(marks[0])):
    marks_transpose.append([])
    for i in range(len(marks)):
        marks_transpose[j].append(marks[i][j])

In [191]:
marks_transpose

[[11, 22, 25], [23, 12, 24], [23, 23, 24], [22, 19, 24]]

In [193]:
marks_arr = np.array(marks)

In [194]:
marks_arr

array([[11, 23, 23, 22],
       [22, 12, 23, 19],
       [25, 24, 24, 24]])

In [195]:
marks_arr.T

array([[11, 22, 25],
       [23, 12, 24],
       [23, 23, 24],
       [22, 19, 24]])

In [200]:
 marks_arr.sum(axis=1)

array([79, 76, 97])

In [197]:
marks_arr.sum(axis=0)

array([58, 59, 70, 65])

In [202]:
# each marks are out of 25
# percentage
marks_arr.sum(axis=1)/100*100

array([79., 76., 97.])

In [203]:
 marks_arr.T.sum(axis=1)

array([58, 59, 70, 65])

In [204]:
marks_arr

array([[11, 23, 23, 22],
       [22, 12, 23, 19],
       [25, 24, 24, 24]])

In [213]:
grace_marks = np.array([[1,2,3]])

In [214]:
grace_marks

array([[1, 2, 3]])

In [215]:
grace_marks.shape

(1, 3)

In [218]:
grace_marks = grace_marks.T

In [221]:
grace_marks.shape

(3, 1)

In [222]:
marks_arr + grace_marks

array([[12, 24, 24, 23],
       [24, 14, 25, 21],
       [28, 27, 27, 27]])

In [224]:
marks_arr = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [225]:
marks_arr

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [227]:
marks_arr = np.array(marks_arr)

In [228]:
marks_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [309]:
weights = np.array([[0.4,0.2,0.2,0.2]])

In [310]:
weights

array([[0.4, 0.2, 0.2, 0.2]])

In [304]:
weights.shape

(4,)

In [273]:
weights.T

array([[0.4],
       [0.2],
       [0.2],
       [0.2]])

In [255]:
weighted_marks = marks_arr * weights

In [256]:
weighted_marks

array([[0.4, 0.4, 0.6, 0.8],
       [2. , 1.2, 1.4, 1.6],
       [3.6, 2. , 2.2, 2.4]])

In [305]:
print(weights)
print(weights.shape)
weighted_marks_arr = []
temp = 0
for i in range(len(marks_arr)):
    for j in range(len(marks_arr[0])):
        temp += marks_arr[i][j]*weights[j];
    weighted_marks_arr.append(temp)
    temp = 0

[0.4 0.2 0.2 0.2]
(4,)


In [306]:
np.array(weighted_marks_arr)

array([ 2.2,  6.2, 10.2])

In [313]:
marks_arr @ weights.T

array([[ 2.2],
       [ 6.2],
       [10.2]])

In [314]:
marks_arr.dot(weights.T)

array([[ 2.2],
       [ 6.2],
       [10.2]])